name: build web
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/image.yml
      - docker/images/**
jobs:
  push:
    name: craftsnet_addons:${{ matrix.tag }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        tag:
          - php8_3-webserver
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./docker/images/${{ matrix.tag }}
          file: ./docker/images/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/craftsblock/craftsnet_addons:${{ matrix.tag }}